import { defineStore } from "pinia";

export const useSettingsStore = defineStore("settings", {
  state: () => ({
    engine_version: 0.6,
    active_experimental_models: [],
    modeling_stepsize: 0.0005,
    base_model_settings: {
      Name: { type: "String", default: "" },
      Description: { type: "String", default: "" },
      ModelType: { type: "String", default: "" },
      IsEnabled: { type: "Boolean", default: false },
    },
    core_models: {
      BloodCompliance: {
        inputs: {
          Vol: { type: "Number", default: 0.001, unit: "l" },
          UVol: { type: "Number", default: 0.0, unit: "l" },
          ElBase: { type: "Number", default: 0.0, unit: "mmHg/l" },
          ElK: { type: "Number", default: 0.0, unit: "mmHg/l" },
        },
        outputs: {
          Vol: { type: "Number", default: 0.001, unit: "l" },
          Pres: { type: "Number", default: 0.0, unit: "mmHg" },
          PresMin: { type: "Number", default: 0.0, unit: "mmHg" },
          PresMax: { type: "Number", default: 0.0, unit: "mmHg" },
          Pres0: { type: "Number", default: 0.0, unit: "mmHg/l" },
          PresExt: { type: "Number", default: 0.0, unit: "mmHg/l" },
          PresMus: { type: "Number", default: 0.0, unit: "mmHg/l" },
          PresCC: { type: "Number", default: 0.0, unit: "mmHg/l" },
          Vol: { type: "Number", default: 0.0, unit: "l" },
          VolMin: { type: "Number", default: 0.0, unit: "l" },
          VolMax: { type: "Number", default: 0.0, unit: "l" },
          So2: { type: "Number", default: 0.0, unit: "%" },
          Po2: { type: "Number", default: 0.0, unit: "mmHg" },
          To2: { type: "Number", default: 0.0, unit: "mmol/l" },
          Tco2: { type: "Number", default: 0.0, unit: "mmol/l" },
          Pco2: { type: "Number", default: 0.0, unit: "mmol/l" },
          Ph: { type: "Number", default: 0.0, unit: "" },
          Hco3: { type: "Number", default: 0.0, unit: "mmol/l" },
          Solutes: { type: "Object", default: 0.0, unit: "String:Number" },
        },
      },
      BloodTimeVaryingElastance: {
        inputs: {
          Vol: { type: "Number", default: 0.001, unit: "l" },
          UVol: { type: "Number", default: 0.0, unit: "l" },
          ElMin: { type: "Number", default: 0.0, unit: "mmHg/l" },
          ElMax: { type: "Number", default: 0.0, unit: "mmHg/l" },
          ElK: { type: "Number", default: 0.0, unit: "mmHg/l" },
        },
        outputs: {
          Vol: { type: "Number", default: 0.001, unit: "l" },
          ActFactor: { type: "Number", default: 0.0, unit: "mmHg" },
          Pres: { type: "Number", default: 0.0, unit: "mmHg" },
          PresEd: { type: "Number", default: 0.0, unit: "mmHg" },
          PresEs: { type: "Number", default: 0.0, unit: "mmHg" },
          PresMin: { type: "Number", default: 0.0, unit: "mmHg" },
          PresMax: { type: "Number", default: 0.0, unit: "mmHg" },
          Vol: { type: "Number", default: 0.0, unit: "l" },
          VolMin: { type: "Number", default: 0.0, unit: "l" },
          VolMax: { type: "Number", default: 0.0, unit: "l" },
          So2: { type: "Number", default: 0.0, unit: "%" },
          Po2: { type: "Number", default: 0.0, unit: "mmHg" },
          To2: { type: "Number", default: 0.0, unit: "mmol/l" },
          Tco2: { type: "Number", default: 0.0, unit: "mmol/l" },
          Pco2: { type: "Number", default: 0.0, unit: "mmol/l" },
          Ph: { type: "Number", default: 0.0, unit: "" },
          Hco3: { type: "Number", default: 0.0, unit: "mmol/l" },
          Solutes: { type: "Object", default: 0.0, unit: "String:Number" },
        },
      },
      BloodResistor: {
        inputs: {
          NoFlow: { type: "Boolean", default: false },
          NoBackFlow: { type: "Boolean", default: false },
          CompFrom: {
            type: "String",
            default: "",
            unit: "BloodCompliance|BloodTimeVaryingElastance",
          },
          CompTo: {
            type: "String",
            default: "",
            unit: "BloodCompliance|BloodTimeVaryingElastance",
          },
          RFor: { type: "Number", default: 0.0, unit: "mmHg/l*s" },
          RBack: { type: "Number", default: 0.0, unit: "mmHg/l*s" },
          Rk: { type: "Number", default: 0.0, unit: "mmHg/l*s" },
        },
        outputs: {
          Flow: { type: "Number", default: 0.0, unit: "l/s" },
          FlowForwardSec: {
            type: "Number",
            default: 0.0,
            unit: "l/s",
          },
          FlowBackwardSec: {
            type: "Number",
            default: 0.0,
            unit: "l/s",
          },
          FlowSec: { type: "Number", default: 0.0, unit: "l/s" },
          Res: { type: "Number", default: 0.0, unit: "mmHg/l*s" },
        },
      },
      GasCompliance: {
        inputs: {
          Vol: { type: "Number", default: 0.001, unit: "l" },
          UVol: { type: "Number", default: 0.0, unit: "l" },
          ElBase: { type: "Number", default: 0.0, unit: "mmHg/l" },
          ElK: { type: "Number", default: 0.0, unit: "mmHg/l" },
          Humidity: { type: "Number", default: 0.0, unit: "" },
          Temp: { type: "Number", default: 0.0, unit: "C" },
          FixedComposition: { type: "Boolean", default: 0.0, unit: "C" },
        },
        outputs: {
          Pres: { type: "Number", default: 0.0, unit: "mmHg/l" },
          PresMin: { type: "Number", default: 0.0, unit: "mmHg" },
          PresMax: { type: "Number", default: 0.0, unit: "mmHg" },
          Pres0: { type: "Number", default: 0.0, unit: "mmHg/l" },
          PresExt: { type: "Number", default: 0.0, unit: "mmHg/l" },
          PresMus: { type: "Number", default: 0.0, unit: "mmHg/l" },
          PresCC: { type: "Number", default: 0.0, unit: "mmHg/l" },
          Temp: { type: "Number", default: 0.0, unit: "C" },
          TargetTemp: { type: "Number", default: 0.0, unit: "C" },
          Humidity: { type: "Number", default: 0.0, unit: "" },
          Ctotal: { type: "Number", default: 0.0, unit: "" },
          Co2: { type: "Number", default: 0.0, unit: "" },
          Cco2: { type: "Number", default: 0.0, unit: "" },
          Cn2: { type: "Number", default: 0.0, unit: "" },
          Ch2o: { type: "Number", default: 0.0, unit: "" },
          Cother: { type: "Number", default: 0.0, unit: "" },
          Po2: { type: "Number", default: 0.0, unit: "" },
          Pco2: { type: "Number", default: 0.0, unit: "" },
          Pn2: { type: "Number", default: 0.0, unit: "" },
          Ph2o: { type: "Number", default: 0.0, unit: "" },
          Pother: { type: "Number", default: 0.0, unit: "" },
          Fo2: { type: "Number", default: 0.0, unit: "" },
          Fco2: { type: "Number", default: 0.0, unit: "" },
          Fn2: { type: "Number", default: 0.0, unit: "" },
          Fh2o: { type: "Number", default: 0.0, unit: "" },
          Fother: { type: "Number", default: 0.0, unit: "" },
        },
      },
      GasResistor: {
        inputs: {
          NoFlow: { type: "Boolean", default: false },
          NoBackFlow: { type: "Boolean", default: false },
          CompFrom: { type: "String", default: "", unit: "GasCompliance" },
          CompTo: { type: "String", default: "", unit: "GasCompliance" },
          RFor: { type: "Number", default: 0.0, unit: "mmHg/l*s" },
          RBack: { type: "Number", default: 0.0, unit: "mmHg/l*s" },
          Rk: { type: "Number", default: 0.0, unit: "mmHg/l*s" },
        },
        outputs: {
          Flow: { type: "Number", default: 0.0, unit: "l/s" },
          FlowForwardSec: {
            type: "Number",
            default: 0.0,
            unit: "l/s",
          },
          FlowBackwardSec: {
            type: "Number",
            default: 0.0,
            unit: "l/s",
          },
          FlowSec: { type: "Number", default: 0.0, unit: "l/s" },
          Res: { type: "Number", default: 0.0, unit: "mmHg/l*s" },
        },
      },
      Container: {
        inputs: {
          ContainedModels: {
            type: "Array",
            default: [],
            unit: "BloodCompliance|BloodTimeVaryingElastance|GasCompliance|Container",
          },
          Vol: { type: "Number", default: 0.001, unit: "l" },
          VolExt: { type: "Number", default: 0.001, unit: "l" },
          UVol: { type: "Number", default: 0.0, unit: "l" },
          ElBase: { type: "Number", default: 0.0, unit: "mmHg/l" },
          ElK: { type: "Number", default: 0.0, unit: "mmHg/l" },
        },
        outputs: {
          Vol: { type: "Number", default: 0.001, unit: "l" },
          Pres: { type: "Number", default: 0.0, unit: "mmHg" },
          PresMin: { type: "Number", default: 0.0, unit: "mmHg" },
          PresMax: { type: "Number", default: 0.0, unit: "mmHg" },
          Pres0: { type: "Number", default: 0.0, unit: "mmHg/l" },
          PresExt: { type: "Number", default: 0.0, unit: "mmHg/l" },
          PresMus: { type: "Number", default: 0.0, unit: "mmHg/l" },
          PresCC: { type: "Number", default: 0.0, unit: "mmHg/l" },
          Vol: { type: "Number", default: 0.0, unit: "l" },
          VolMin: { type: "Number", default: 0.0, unit: "l" },
          VolMax: { type: "Number", default: 0.0, unit: "l" },
        },
      },
      GasExchanger: {
        inputs: {
          CompBlood: {
            type: "String",
            default: "",
            unit: "BloodCompliance|BloodTimeVaryingElastance",
          },
          CompGas: { type: "String", default: "", unit: "GasCompliance" },
          DiffO2: { type: "Number", default: 0.01, unit: "" },
          DiffCo2: { type: "Number", default: 0.01, unit: "" },
        },
        outputs: {
          FluxO2: { type: "Number", default: 0.01, unit: "" },
          FluxCo2: { type: "Number", default: 0.01, unit: "" },
        },
      },
      Heart: {
        inputs: {
          RightAtrium: {
            type: "String",
            unit: "BloodTimeVaryingElastance",
            default: "",
          },
          LeftAtrium: {
            type: "String",
            unit: "BloodTimeVaryingElastance",
            default: "",
          },
          RightVentricle: {
            type: "String",
            unit: "BloodTimeVaryingElastance",
            default: "",
          },
          LeftVentricle: {
            type: "String",
            unit: "BloodTimeVaryingElastance",
            default: "",
          },
          Coronaries: {
            type: "String",
            unit: "BloodTimeVaryingElastance",
            default: "",
          },
          HeartRate: { type: "Number", default: 0.0, unit: "/min" },
          HeartRateRef: { type: "Number", default: 0.0, unit: "/min" },
          HeartRateUpperLimit: { type: "Number", default: 0.0, unit: "/min" },
          VenticularEscapeRate: { type: "Number", default: 0.0, unit: "/min" },
          RhythmType: { type: "Number", default: 0.0, unit: "" },
          PqTime: { type: "Number", default: 0.0, unit: "s" },
          AvDelay: { type: "Number", default: 0.0, unit: "s" },
          QrsTime: { type: "Number", default: 0.0, unit: "s" },
          QtTime: { type: "Number", default: 0.0, unit: "s" },
          CqtTime: { type: "Number", default: 0.0, unit: "s" },
        },
        outputs: {
          HeartPeriodChangeAns: { type: "Number", default: 0.0, unit: "" },
          HeartPeriodChangeTemp: { type: "Number", default: 0.0, unit: "" },
          HeartPeriodChangeMyo: { type: "Number", default: 0.0, unit: "" },
          CqtTime: { type: "Number", default: 0.0, unit: "s" },
          NccAtrial: { type: "Number", default: 0.0, unit: "s" },
          NccVentricular: { type: "Number", default: 0.0, unit: "s" },
          Aaf: { type: "Number", default: 0.0, unit: "s" },
          Vaf: { type: "Number", default: 0.0, unit: "s" },
        },
      },
      Metabolism: {
        inputs: {
          Vo2: { type: "Number", default: 8.5, unit: "mmol/s" },
          RespQ: { type: "Number", default: 0.8, unit: "" },
          BodyTemp: { type: "Number", default: 37.0, unit: "mmol/s" },
          MetabolicActiveModels: {
            type: "Object",
            default: {},
            unit: "BloodCompliance|BloodTimeVaryingElastance:Number",
          },
        },
        outputs: {},
      },
      Blood: {
        inputs: {
          To2: { type: "Number", default: 8.5, unit: "mmol/l" },
          Tco2: { type: "Number", default: 8.5, unit: "mmol/l" },
          Solutes: { type: "Object", default: {}, unit: "String:Number" },
        },
        outputs: {},
      },
      Gas: {
        inputs: {
          PresAtm: { type: "Number", default: 760, unit: "mmHg" },
          DryAir: { type: "Object", default: {}, unit: "" },
          HumiditySettings: {
            type: "Object",
            default: {},
            unit: "GasCompliance:Number",
          },
          TempSettings: {
            type: "Object",
            default: {},
            unit: "GasCompliance:Number",
          },
        },
        outputs: {},
      },
      Breathing: {
        inputs: {
          BreathingEnabled: { type: "Boolean", default: true },
          RespRate: { type: "Number", default: 0.0, unit: "/min" },
          RefMinuteVolume: { type: "Number", default: 0.0, unit: "l/min" },
          RefTidalVolume: { type: "Number", default: 0.0, unit: "l" },
          TargetMinuteVolume: { type: "Number", default: 0.0, unit: "l/min" },
          TargetTidalVolume: { type: "Number", default: 0.0, unit: "l" },
          VtRrRatio: { type: "Number", default: 0.0, unit: "" },
          RespMusclePressure: { type: "Number", default: 0.0, unit: "" },
          RmpGain: { type: "Number", default: 0.0, unit: "" },
          Targets: {
            type: "[String]",
            default: [],
            unit: "Container|GasCompliance|BloodCompliance|BloodTimeVaryingElastance",
          },
          TidalVolumeSource: {
            type: "String",
            default: "",
            unit: "GasResistor",
          },
        },
        outputs: {
          RespRate: { type: "Number", default: 0.0, unit: "/min" },
          InspTidalVolume: { type: "Number", default: 0.0, unit: "l" },
          ExpTidalVolume: { type: "Number", default: 0.0, unit: "l" },
          MinuteVolume: { type: "Number", default: 0.0, unit: "l/min" },
          RespMusclePressure: { type: "Number", default: 0.0, unit: "" },
          RmpGain: { type: "Number", default: 0.0, unit: "" },
        },
      },
      AutonomicNervousSystem: {
        inputs: {
          UpdateInterval: {
            type: "Number",
            default: 0.015,
            unit: "s",
          },
          HeartModelName: {
            type: "String",
            default: "",
            unit: "Heart",
          },
          BreathingModelName: {
            type: "String",
            default: "",
            unit: "Breathing",
          },
          SystemicResistors: {
            type: "Array",
            default: [],
            unit: "BloodResistors",
          },
          UnstressedVolumes: {
            type: "Array",
            default: [],
            unit: "BloodCompliance|BloodTimeVaryingElastance",
          },
          BaroreceptorLocation: {
            type: "String",
            default: "",
            unit: "BloodCompliance|BloodTimeVaryingElastance",
          },
          ChemoreceptorLocation: {
            type: "String",
            default: "",
            unit: "BloodCompliance|BloodTimeVaryingElastance",
          },
          LungCompartments: {
            type: "Array",
            default: [],
            type: "GasCompliance|Container",
          },
          SetBaro: { type: "Number", default: 0.0, unit: "" },
          MinBaro: { type: "Number", default: 0.0, unit: "" },
          MaxBaro: { type: "Number", default: 0.0, unit: "" },
          TcHpBaro: { type: "Number", default: 0.0, unit: "" },
          TcContBaro: { type: "Number", default: 0.0, unit: "" },
          TcResBaro: { type: "Number", default: 0.0, unit: "" },
          TcUvolBaro: { type: "Number", default: 0.0, unit: "" },
          GHpBaro: { type: "Number", default: 0.0, unit: "" },
          GContBaro: { type: "Number", default: 0.0, unit: "" },
          GResBaro: { type: "Number", default: 0.0, unit: "" },
          GUvolBaro: { type: "Number", default: 0.0, unit: "" },
          SetPo2: { type: "Number", default: 0.0, unit: "" },
          MinPo2: { type: "Number", default: 0.0, unit: "" },
          MaxPo2: { type: "Number", default: 0.0, unit: "" },
          TcHpPo2: { type: "Number", default: 0.0, unit: "" },
          TcVePo2: { type: "Number", default: 0.0, unit: "" },
          GHpPo2: { type: "Number", default: 0.0, unit: "" },
          GVePo2: { type: "Number", default: 0.0, unit: "" },
          SetPco2: { type: "Number", default: 0.0, unit: "" },
          MinPco2: { type: "Number", default: 0.0, unit: "" },
          MaxPco2: { type: "Number", default: 0.0, unit: "" },
          TcHpPco2: { type: "Number", default: 0.0, unit: "" },
          TcVePco2: { type: "Number", default: 0.0, unit: "" },
          GHpPco2: { type: "Number", default: 0.0, unit: "" },
          GVePco2: { type: "Number", default: 0.0, unit: "" },
          SetPh: { type: "Number", default: 0.0, unit: "" },
          MinPh: { type: "Number", default: 0.0, unit: "" },
          MaxPh: { type: "Number", default: 0.0, unit: "" },
          TcVePh: { type: "Number", default: 0.0, unit: "" },
          GVePh: { type: "Number", default: 0.0, unit: "" },
          SetLungStretch: { type: "Number", default: 0.0, unit: "" },
          MinLungStretch: { type: "Number", default: 0.0, unit: "" },
          MaxLungStretch: { type: "Number", default: 0.0, unit: "" },
          TcVeLungStretch: { type: "Number", default: 0.0, unit: "" },
          GVeLungStretch: { type: "Number", default: 0.0, unit: "" },
        },
        outputs: {
          HeartPeriodChangeAns: { type: "Number", default: 0.0, unit: "" },
          TargetMinuteVolume: { type: "Number", default: 0.0, unit: "" },
        },
      },
      AcidBase: {
        inputs: {
          Tco2: { type: "Number", default: 24.7, unit: "mmol/l" },
          Sid: { type: "Number", default: 35.9, unit: "mmol/l" },
          Alb: { type: "Number", default: 25.0, unit: "g/l" },
          Pi: { type: "Number", default: 1.64, unit: "mmol/l" },
          U: { type: "Number", default: 0.0, unit: "mmol/l" },
          AlphaCo2P: { type: "Number", default: 0.03067, unit: "" },
        },
        outputs: {
          Ph: { type: "Number", default: 0.0, unit: "" },
          Pco2: { type: "Number", default: 0.0, unit: "" },
          Hco3: { type: "Number", default: 0.0, unit: "" },
        },
      },
      Oxygenation: {
        inputs: {
          To2: { type: "Number", default: 8.7, unit: "mmol/l" },
          Hb: { type: "Number", default: 8.0, unit: "mmol/l" },
          Temp: { type: "Number", default: 37.0, unit: "C" },
          Ph: { type: "Number", default: 7.4, unit: "" },
          Be: { type: "Number", default: 0.0, unit: "mmol/l" },
          Dpg: { type: "Number", default: 5.0, unit: "mmol/l" },
          Pres: { type: "Number", default: 760, unit: "mmHg" },
        },
        outputs: {
          So2: { type: "Number", default: 0.0, unit: "" },
          Po2: { type: "Number", default: 0.0, unit: "" },
        },
      },
    },
    experimental_models: {
      ArtificalWhomb: { inputs: {}, outputs: {} },
      Birth: { inputs: {}, outputs: {} },
      ChestCompressions: { inputs: {}, outputs: {} },
      Cvvh: { inputs: {}, outputs: {} },
      Drugs: { inputs: {}, outputs: {} },
      ECMO: { inputs: {}, outputs: {} },
      IntrathoracicPressure: { inputs: {}, outputs: {} },
      Kidneys: { inputs: {}, outputs: {} },
      MechanicalVentilator: {
        inputs: {
          VolumeGaranteed: { type: "Boolean", default: false, unit: "" },
          PipMax: { type: "Number", default: 0.0, unit: "" },
          VtSet: { type: "Number", default: 0.0, unit: "" },
          InspTime: { type: "Number", default: 0.0, unit: "" },
          Freq: { type: "Number", default: 0.0, unit: "" },
          Pip: { type: "Number", default: 0.0, unit: "" },
          Peep: { type: "Number", default: 0.0, unit: "" },
          InspFlow: { type: "Number", default: 0.0, unit: "" },
          ExpFlow: { type: "Number", default: 0.0, unit: "" },
          Temp: { type: "Number", default: 0.0, unit: "" },
          Humidity: { type: "Number", default: 0.0, unit: "" },
          Fo2Dry: { type: "Number", default: 0.0, unit: "" },
          Fco2Dry: { type: "Number", default: 0.0, unit: "" },
          Fn2Dry: { type: "Number", default: 0.0, unit: "" },
          FotherDry: { type: "Number", default: 0.0, unit: "" },
          VentInModel: { type: "String", default: 0.0, unit: "GasCompliance" },
          VentInInternalPressure: { type: "Number", default: 0.0, unit: "" },
          VentInVolume: { type: "Number", default: 0.0, unit: "" },
          VentInElastance: { type: "Number", default: 0.0, unit: "" },
          TubingModel: { type: "Array", default: 0.0, unit: "GasCompliance" },
          TubingLength: { type: "Number", default: 0.0, unit: "" },
          TubingInnerDiameter: { type: "Number", default: 0.0, unit: "" },
          TubingElastance: { type: "Number", default: 0.0, unit: "" },
          YpieceModel: { type: "String", default: 0.0, unit: "GasCompliance" },
          YpieceVolume: { type: "Number", default: 0.0, unit: "" },
          YpieceElastance: { type: "Number", default: 0.0, unit: "" },
          VentOutModel: { type: "String", default: 0.0, unit: "GasCompliance" },
          VentOutInternalPressure: { type: "Number", default: 0.0, unit: "" },
          VentOutVolume: { type: "Number", default: 0.0, unit: "" },
          VentOutElastance: { type: "Number", default: 0.0, unit: "" },
          VentOutHumidity: { type: "Number", default: 0.0, unit: "" },
          VentOutTemp: { type: "Number", default: 0.0, unit: "" },
          VentOutFo2Dry: { type: "Number", default: 0.0, unit: "" },
          VentOutFco2Dry: { type: "Number", default: 0.0, unit: "" },
          VentOutFn2Dry: { type: "Number", default: 0.0, unit: "" },
          VentOutFotherDry: { type: "Number", default: 0.0, unit: "" },
        },
        outputs: {
          Inspiration: { type: "Boolean", default: 0.0, unit: "" },
          Expiration: { type: "Boolean", default: 0.0, unit: "" },
          VtInsp: { type: "Number", default: 0.0, unit: "" },
          VtExp: { type: "Number", default: 0.0, unit: "" },
          EtCo2_signal: { type: "Number", default: 0.0, unit: "" },
          EtCo2: { type: "Number", default: 0.0, unit: "" },
          ExpTime: { type: "Number", default: 0.0, unit: "" },
          Flow: { type: "Number", default: 0.0, unit: "" },
          Pres: { type: "Number", default: 0.0, unit: "" },
          Vol: { type: "Number", default: 0.0, unit: "" },
        },
      },
      Myocardium: {
        inputs: {
          HeartModelName: { type: "String", default: "", unit: "Heart" },
          LeftVentricleName: {
            type: "String",
            default: 0.0,
            unit: "BloodTimeVaryingElastance",
          },
          RightVentricleName: {
            type: "String",
            default: 0.0,
            unit: "BloodTimeVaryingElastance",
          },
          CoronariesName: {
            type: "String",
            default: 0.0,
            unit: "BloodCompliance|BloodTimeVaryingElastance",
          },
          SetTo2: { type: "Number", default: 0.0, unit: "" },
          MinTo2: { type: "Number", default: 0.0, unit: "" },
          MaxTo2: { type: "Number", default: 0.0, unit: "" },
          TcHpTo2: { type: "Number", default: 0.0, unit: "" },
          TcContTo2: { type: "Number", default: 0.0, unit: "" },
          GHpTo2: { type: "Number", default: 0.0, unit: "" },
          GContTo2: { type: "Number", default: 0.0, unit: "" },
        },
        outputs: {},
      },
      Pda: {
        inputs: {
          Model: { type: "String", default: 0.0, unit: "BloodResistor" },
          Length: { type: "Number", default: 0.0, unit: "" },
          Diameter: { type: "Number", default: 0.0, unit: "" },
          Viscosity: { type: "Number", default: 0.0, unit: "" },
        },
        outputs: {
          Res: { type: "Number", default: 0.0, unit: "" },
          Velocity: { type: "Number", default: 0.0, unit: "" },
          Flow: { type: "Number", default: 0.0, unit: "" },
        },
      },
      Placenta: { inputs: {}, outputs: {} },
      Raas: { inputs: {}, outputs: {} },
      Resuscitation: { inputs: {}, outputs: {} },
    },
  }),

  getters: {},

  actions: {},
});
