import { defineStore } from "pinia";

export const useUserInterfaceStore = defineStore("userInterface", {
  state: () => ({
    models: {
      BloodTimeVaryingElastance: {
        properties: [
          {
            modelProp: "Vol",
            typeProp: "numeric",
            caption: "volume",
            unit: "mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 1000.0,
            displayRounding: 2,
          },
          {
            modelProp: "UVol",
            caption: "UVol",
            typeProp: "numeric",
            unit: "mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 1000.0,
            displayRounding: 2,
          },
          {
            caption: "ElMin",
            modelProp: "ElMin",
            typeProp: "numeric",
            unit: "mmHg/mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "ElMax",
            modelProp: "ElMax",
            typeProp: "numeric",
            unit: "mmHg/mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "ElK",
            modelProp: "ElK",
            typeProp: "numeric",
            unit: "mmHg/mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "Enabled",
            modelProp: "IsEnabled",
            typeProp: "boolean",
          },
        ],
      },
      BloodCompliance: {
        properties: [
          {
            modelProp: "Vol",
            typeProp: "numeric",
            caption: "volume",
            unit: "mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 1000.0,
            displayRounding: 2,
          },
          {
            modelProp: "UVol",
            caption: "UVol",
            typeProp: "numeric",
            unit: "mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 1000.0,
            displayRounding: 2,
          },
          {
            caption: "ElBase",
            modelProp: "ElBase",
            typeProp: "numeric",
            unit: "mmHg/mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "ElK",
            modelProp: "ElK",
            typeProp: "numeric",
            unit: "mmHg/mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "Enabled",
            modelProp: "IsEnabled",
            typeProp: "boolean",
          },
        ],
      },
      BloodResistor: {
        properties: [
          {
            caption: "RFor",
            modelProp: "RFor",
            typeProp: "numeric",
            unit: "mL/mmHg*s",
            min: 0.02,
            step: 0.1,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "RBack",
            modelProp: "RBack",
            typeProp: "numeric",
            unit: "mL/mmHg*s",
            min: 0.02,
            step: 0.1,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "Rk",
            modelProp: "Rk",
            typeProp: "numeric",
            unit: "mL/mmHg*s",
            min: 0.02,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "Enabled",
            modelProp: "IsEnabled",
            typeProp: "boolean",
          },
          {
            caption: "NoFlow",
            modelProp: "NoFlow",
            typeProp: "boolean",
          },
          {
            caption: "NoBackFlow",
            modelProp: "NoBackFlow",
            typeProp: "boolean",
          },
          {
            caption: "from",
            modelProp: "CompFrom",
            typeProp: "list",
            optionalModels: ["BloodCompliance", "BloodTimeVaryingElastance"],
          },
          {
            caption: "to",
            modelProp: "CompTo",
            typeProp: "list",
            optionalModels: ["BloodCompliance", "BloodTimeVaryingElastance"],
          },
        ],
      },
      GasCompliance: {
        properties: [
          {
            modelProp: "Vol",
            typeProp: "numeric",
            caption: "volume",
            unit: "mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 1000.0,
            displayRounding: 2,
          },
          {
            modelProp: "UVol",
            caption: "UVol",
            typeProp: "numeric",
            unit: "mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 1000.0,
            displayRounding: 2,
          },
          {
            caption: "ElBase",
            modelProp: "ElBase",
            typeProp: "numeric",
            unit: "mmHg/mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "ElK",
            modelProp: "ElK",
            typeProp: "numeric",
            unit: "mmHg/mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "Enabled",
            modelProp: "IsEnabled",
            typeProp: "boolean",
          },
        ],
      },
      Container: {
        properties: [
          {
            modelProp: "Vol",
            typeProp: "numeric",
            caption: "volume",
            unit: "mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 1000.0,
            displayRounding: 2,
          },
          {
            modelProp: "UVol",
            caption: "UVol",
            typeProp: "numeric",
            unit: "mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 1000.0,
            displayRounding: 2,
          },
          {
            caption: "ElBase",
            modelProp: "ElBase",
            typeProp: "numeric",
            unit: "mmHg/mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "ElK",
            modelProp: "ElK",
            typeProp: "numeric",
            unit: "mmHg/mL",
            min: 0.0,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "Enabled",
            modelProp: "IsEnabled",
            typeProp: "boolean",
          },
          {
            caption: "contained models",
            modelProp: "ContainedModels",
            typeProp: "multilist",
            optionalModels: [
              "BloodCompliance",
              "BloodTimeVaryingElastance",
              "GasCompliance",
              "Container",
            ],
          },
        ],
      },
      GasResistor: {
        properties: [
          {
            caption: "RFor",
            modelProp: "RFor",
            typeProp: "numeric",
            unit: "mL/mmHg*s",
            min: 0.001,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "RBack",
            modelProp: "RBack",
            typeProp: "numeric",
            unit: "mL/mmHg*s",
            min: 0.001,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "Rk",
            modelProp: "Rk",
            typeProp: "numeric",
            unit: "mL/mmHg*s",
            min: 0.001,
            step: 0.01,
            displayFactor: 0.001,
            displayRounding: 2,
          },
          {
            caption: "Enabled",
            modelProp: "IsEnabled",
            typeProp: "boolean",
          },
          {
            caption: "NoFlow",
            modelProp: "NoFlow",
            typeProp: "boolean",
          },
          {
            caption: "NoBackFlow",
            modelProp: "NoBackFlow",
            typeProp: "boolean",
          },
          {
            caption: "from",
            modelProp: "CompFrom",
            typeProp: "list",
            optionalModels: ["GasCompliance"],
          },
          {
            caption: "to",
            modelProp: "CompTo",
            typeProp: "list",
            optionalModels: ["GasCompliance"],
          },
        ],
      },
      GasExchanger: {
        properties: [
          {
            caption: "DifO2",
            modelProp: "DifO2",
            typeProp: "numeric",
            unit: "mmol/mmHg",
            min: 0.0,
            step: 0.01,
            displayFactor: 1000.0,
            displayRounding: 2,
          },
          {
            caption: "DifCo2",
            modelProp: "DifCo2",
            typeProp: "numeric",
            unit: "mmol/mmHg",
            min: 0.0,
            step: 0.01,
            displayFactor: 1000.0,
            displayRounding: 2,
          },
          {
            caption: "Gas",
            modelProp: "CompGas",
            typeProp: "list",
            optionalModels: ["GasCompliance"],
          },
          {
            caption: "Blood",
            modelProp: "CompBlood",
            typeProp: "list",
            optionalModels: ["BloodCompliance", "BloodTimeVaryingElastance"],
          },
        ],
      },
      ArtificialWhomb: {},
      AutonomicNervousSystem: {},
      Birth: {},
      Blood: {},
      Breathing: {},
      ChestCompressions: {},
      Cvvh: {},
      Drugs: {},
      ECMO: {},
      Gas: {},
      Heart: {},
      IntrathoracicPressure: {},
      Kidneys: {},
      MechanicalVentilator: {},
      Metabolism: {},
      Myocardium: {},
      Oxygenation: {},
      Pda: {},
      Placenta: {},
      Raas: {},
      Resuscitation: {},
    },
    groupers: {
      heart: {
        rhythm: {
          caption: "Heart rhythm",
          caption1: "",
          caption2: "",
          value: 1.0,
          min: 0.0,
          max: 10.0,
          closable: false,
          splittable: false,
          single: true,
          properties: [
            {
              model: "Heart",
              modelProp: "RhythmType",
              typeProp: "numeric",
              factor: 1.0,
            },
          ],
        },
        contraction: {
          caption: "Contraction",
          caption1: "LV",
          caption2: "RV",
          min: 0.0,
          max: 500.0,
          closable: false,
          splittable: true,
          single: true,
          properties: [
            {
              model: "LV",
              modelProp: "ElMax",
              typeProp: "numeric",
              factor: 1.0,
            },
            {
              model: "RV",
              modelProp: "ElMax",
              typeProp: "numeric",
              factor: 1.0,
            },
          ],
        },
        relaxation: {
          caption: "Relaxation",
          value: 100.0,
          min: 0.0,
          max: 1000.0,
          properties: [
            {
              model: "LV",
              modelProp: "ElMin",
              typeProp: "numeric",
              factor: 1.0,
            },
            {
              model: "RV",
              modelProp: "ElMin",
              typeProp: "numeric",
              factor: 1.0,
            },
          ],
        },
      },
      valves: {
        aorticValveStenosis: {
          properties: [
            {
              model: "LV_AA",
              modelProp: "RFor",
              typeProp: "numeric",
              factor: 1.0,
            },
          ],
        },
        aorticValveRegurgitation: {
          properties: [
            {
              model: "LV_AA",
              modelProp: "RBack",
              typeProp: "numeric",
              factor: 1.0,
            },
            {
              model: "LV_AA",
              modelProp: "NoBackflow",
              typeProp: "boolean",
              factor: 1.0,
            },
          ],
        },
        pulmonaryValveStenosis: {
          properties: [
            {
              model: "RV_PA",
              modelProp: "RFor",
              typeProp: "numeric",
              factor: 1.0,
            },
          ],
        },
        pulmonaryValveRegurgitation: {
          properties: [
            {
              model: "RV_PA",
              modelProp: "RBack",
              typeProp: "numeric",
              factor: 1.0,
            },
            {
              model: "RV_PA",
              modelProp: "NoBackflow",
              typeProp: "boolean",
              factor: 1.0,
            },
          ],
        },
        mitralValveStenosis: {
          properties: [
            {
              model: "LA_LV",
              modelProp: "RFor",
              typeProp: "numeric",
              factor: 1.0,
            },
          ],
        },
        mitralValveRegurgitation: {
          properties: [
            {
              model: "LA_LV",
              modelProp: "RBack",
              typeProp: "numeric",
              factor: 1.0,
            },
            {
              model: "RV_PA",
              modelProp: "NoBackflow",
              typeProp: "boolean",
              factor: 1.0,
            },
          ],
        },
        tricuspidValveStenosis: {
          properties: [
            {
              model: "RA_RV",
              modelProp: "RFor",
              typeProp: "numeric",
              factor: 1.0,
            },
          ],
        },
        tricuspidValveRegurgitation: {
          properties: [
            {
              model: "RA_RV",
              modelProp: "RBack",
              typeProp: "numeric",
              factor: 1.0,
            },
            {
              model: "RA_RV",
              modelProp: "NoBackflow",
              typeProp: "boolean",
              factor: 1.0,
            },
          ],
        },
      },
      pericardium: {},
      circulation: {
        intravascularVolume: {
          properties: [{}],
        },
        systemicVascularResistance: {
          properties: [{}],
        },
        pulmonaryVascularResistance: {
          properties: [{}],
        },
        coronaryVascularResistance: {
          properties: [{}],
        },
        venousPooling: {
          properties: [{}],
        },
        arterialCompliance: {
          properties: [{}],
        },
        venousCompliance: {
          properties: [{}],
        },
      },
      shunts: {
        pdaSize: {
          properties: [{}],
        },
        ofoSize: { properties: [{}] },
        vsdSize: {
          properties: [{}],
        },
        lungShuntSize: {
          properties: [{}],
        },
      },
      airways: {},
      breathing: {},
      ventilation: {},
      lungs: {},
      chestwall: {},
      gasexchange: {},
      intrathoracicPressure: {},
      mechanicalVentilator: {},
      metabolism: {},
      autonomicNervousSystem: {},
      acidbase: {},
      oxygenation: {},
      blood: {},
      gas: {},
      ecmo: {},
      artificialWhomb: {},
      drugs: {},
      kidneys: {},
      resuscitation: {},
      cvvh: {},
      placenta: {},
      raas: {},
      birth: {},
    },
    charts: {
      gasFlowProbe: {
        enabled: true,
        collapsed: true,
        title: "GAS FLOW PROBE",
        models: [],
        modelProps: [],
      },
      gasPressureProbe: {
        enabled: true,
        collapsed: true,
        title: "GAS PRESSURE PROBE",
        models: [],
        modelProps: [],
      },
      bloodFlowProbe: {
        enabled: true,
        collapsed: true,
        title: "BLOOD FLOW PROBE",
        models: [],
        modelProps: [],
      },
      bloodPressureProbe: {
        enabled: true,
        collapsed: true,
        title: "BLOOD PRESSURE PROBE",
        models: [],
        modelProps: [],
      },
    },
    monitors: {
      heartMonitoring: {
        enabled: false,
        collapsed: true,
        title: "HEART",
        parameters: [],
      },
      hemodynamicMonitoring: {
        enabled: false,
        collapsed: true,
        title: "HEMODYNAMICS",
        parameters: [],
      },
      respirationMonitoring: {
        enabled: false,
        collapsed: true,
        title: "RESPIRATION",
        parameters: [],
      },
      lungChestwallMonitoring: {
        enabled: false,
        collapsed: true,
        title: "LUNG AND CHESTWALL",
        parameters: [],
      },
      acidbaseAndOxyMonitoring: {
        enabled: true,
        collapsed: true,
        title: "ACIDBASE AND OXYGENATION",
        parameters: [
          {
            model: "AA",
            prop: "Ph",
            label: "Ph",
            unit: "",
            value: 7.43,
            rounding: 2,
          },
          {
            model: "AA",
            prop: "Pco2",
            label: "Pco2",
            unit: "mmHg",
            value: 45,
            rounding: 0,
          },
          {
            model: "AA",
            prop: "Hco3",
            label: "Hco3",
            unit: "mmol/l",
            value: 23.1,
            rounding: 1,
          },
          {
            model: "AA",
            prop: "Po2",
            label: "Po2",
            unit: "mmHg",
            value: 100,
            rounding: 0,
          },
          {
            model: "AA",
            prop: "So2",
            label: "So2",
            unit: "%",
            value: 97,
            rounding: 0,
          },
        ],
      },
      ecmoMonitoring: {
        enabled: false,
        collapsed: true,
        title: "ECMO",
        parameters: [
          {
            model: "LV_AA",
            prop: "Flow",
            label: "Flow",
            unit: "l/min",
            value: 250,
            rounding: 0,
          },
        ],
      },
      drugMonitoring: {
        enabled: false,
        collapsed: true,
        title: "DRUGS",
        parameters: [],
      },
      kidneyMonitoring: {
        enabled: false,
        collapsed: true,
        title: "KIDNEYS",
        parameters: [],
      },
      artificialWhombMonitoring: {
        enabled: false,
        collapsed: true,
        title: "ARTIFICIAL WHOMB",
        parameters: [],
      },
      brainMonitoring: {
        enabled: false,
        collapsed: true,
        title: "BRAIN",
        parameters: [],
      },
      resuscitationMonitoring: {
        enabled: false,
        collapsed: true,
        title: "RESUSCITATION",
        parameters: [],
      },
      birthMonitoring: {
        enabled: false,
        collapsed: true,
        title: "BIRTH",
        parameters: [],
      },
      ansMonitoring: {
        enabled: false,
        collapsed: true,
        title: "AUTONOMIC NERVOUS SYSTEM",
        parameters: [],
      },
      ventilatorMonitoring: {
        enabled: false,
        collapsed: true,
        title: "MECHANICAL VENTILATOR",
        parameters: [],
      },
    },
  }),

  getters: {},

  actions: {},
});
