import { defineStore } from "pinia";

export const useUserInterfaceStore = defineStore("userInterface", {
  state: () => ({
    models: {
      bloodCompliance: {
        label: "Blood compliances",
        collapsed: true,
        model_type: "BloodCompliance",
        properties: ["ElBase", "Vol", "UVol", "ElK"],
      },
      bloodResistor: {
        label: "Blood resistors",
        collapsed: true,
        model_type: "BloodResistor",
        properties: [
          "RFor",
          "RBack",
          "Rk",
          "NoFlow",
          "NoBackFlow",
          "CompFrom",
          "CompTo",
        ],
      },
      bloodTimeVaryingElastance: {
        label: "Blood time varying elastances",
        collapsed: true,
        model_type: "BloodTimeVaryingElastance",
        properties: ["ElMin", "ElMax", "Vol", "UVol", "ElK"],
      },
      gasCompliance: {
        label: "Gas compliances",
        collapsed: true,
        model_type: "GasCompliance",
        properties: ["ElBase", "Vol", "UVol", "ElK"],
      },
      container: {
        label: "Containers",
        collapsed: true,
        model_type: "Container",
        properties: ["Comps", "Vol", "UVol", "ElBase", "ElK"],
      },
      gasResistor: {
        label: "Gas resistors",
        collapsed: true,
        model_type: "GasResistor",
        properties: [
          "RFor",
          "RBack",
          "Rk",
          "NoFlow",
          "NoBackFlow",
          "CompFrom",
          "CompTo",
        ],
      },
      gasExchanger: {
        label: "Gas exchangers",
        collapsed: true,
        model_type: "GasExchanger",
        properties: ["CompBlood", "CompGas", "DifO2", "DifCo2"],
      },
    },
    charts: {
      bloodFlowProbe: {
        enabled: true,
        collapsed: true,
        title: "FLOW PROBE",
        model_types: [],
        model_props: [],
      },
      bloodPressureProbe: {
        enabled: true,
        collapsed: true,
        title: "PRESSURE PROBE",
        model_types: [],
        model_props: [],
      },
    },
    monitors: {
      heartMonitoring: {
        enabled: false,
        collapsed: true,
        title: "HEART",
        parameters: [],
      },
      hemodynamicMonitoring: {
        enabled: false,
        collapsed: true,
        title: "HEMODYNAMICS",
        parameters: [],
      },
      respirationMonitoring: {
        enabled: false,
        collapsed: true,
        title: "RESPIRATION",
        parameters: [],
      },
      lungChestwallMonitoring: {
        enabled: false,
        collapsed: true,
        title: "LUNG AND CHESTWALL",
        parameters: [],
      },
      acidbaseAndOxyMonitoring: {
        enabled: true,
        collapsed: true,
        title: "ACIDBASE AND OXYGENATION",
        parameters: [
          {
            model: "AA",
            prop: "Ph",
            label: "Ph",
            unit: "",
            value: 7.43,
            rounding: 2,
          },
          {
            model: "AA",
            prop: "Pco2",
            label: "Pco2",
            unit: "mmHg",
            value: 45,
            rounding: 0,
          },
          {
            model: "AA",
            prop: "Hco3",
            label: "Hco3",
            unit: "mmol/l",
            value: 23.1,
            rounding: 1,
          },
          {
            model: "AA",
            prop: "Po2",
            label: "Po2",
            unit: "mmHg",
            value: 100,
            rounding: 0,
          },
          {
            model: "AA",
            prop: "So2",
            label: "So2",
            unit: "%",
            value: 97,
            rounding: 0,
          },
        ],
      },
      ecmoMonitoring: {
        enabled: false,
        collapsed: true,
        title: "ECMO",
        parameters: [
          {
            model: "LV_AA",
            prop: "Flow",
            label: "Flow",
            unit: "l/min",
            value: 250,
            rounding: 0,
          },
        ],
      },
      drugMonitoring: {
        enabled: false,
        collapsed: true,
        title: "DRUGS",
        parameters: [],
      },
      kidneyMonitoring: {
        enabled: false,
        collapsed: true,
        title: "KIDNEYS",
        parameters: [],
      },
      artificialWhombMonitoring: {
        enabled: false,
        collapsed: true,
        title: "ARTIFICIAL WHOMB",
        parameters: [],
      },
      brainMonitoring: {
        enabled: false,
        collapsed: true,
        title: "BRAIN",
        parameters: [],
      },
      resuscitationMonitoring: {
        enabled: false,
        collapsed: true,
        title: "RESUSCITATION",
        parameters: [],
      },
      birthMonitoring: {
        enabled: false,
        collapsed: true,
        title: "BIRTH",
        parameters: [],
      },
      ansMonitoring: {
        enabled: false,
        collapsed: true,
        title: "AUTONOMIC NERVOUS SYSTEM",
        parameters: [],
      },
      ventilatorMonitoring: {
        enabled: false,
        collapsed: true,
        title: "MECHANICAL VENTILATOR",
        parameters: [],
      },
    },
  }),

  getters: {},

  actions: {},
});
