FROM node:19-alpine3.16
RUN apk --no-cache add yarn --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
    && yarn global add @quasar/cli
# define a working directory
WORKDIR /app

# expose the port
EXPOSE 8080
